apiVersion: apps/v1
kind: Deployment
metadata:
    name: trial-deployment
    namespace: test
    labels:
        app: Trial-Deployment
spec:
    replicas: 2
    selector: 
        matchLabels:
            app: android
    template:
        metadata:
            labels: 
                app: android
        spec:
         containers:
            - name: testcontainer
              image: docker.io/nizam799/javaapp:v5
              ports:
              - containerPort: 8000
              resources:
                requests:
                   cpu: "100m"
                   memory: "128Mi"
                limits:
                   cpu: "500m"
                   memory: "256Mi"
        